version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
      - frontend

  api-gateway:
    build:
      context: ./services/api-gateway
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/telegram_invite
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis

  worker:
    build:
      context: ./services/worker
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/telegram_invite
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=telegram_invite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 