# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy to server & deploy
          uses: appleboy/ssh-action@v0.1.9
          with:
          host: ${{ secrets.SERVER_HOST }}
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e

            # --- обновляем бекенд, рестартим сервисы ---
            cd ~/telegram_invite
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart telegram_inviter_celery.service telegram_inviter_flask.service

            # --- собираем фронтенд чисто с нуля ---
            cd frontend
            rm -rf dist                 # ← вот это
            npm ci
            npm run build

            # --- отдаем новую сборку ---
            sudo systemctl reload nginx


            sudo systemctl restart telegram_inviter_celery.service
            sudo systemctl restart telegram_inviter_flask.service

            cd frontend
            npm ci
            npm run build

            # чтобы nginx отдал новую статическую сборку
            sudo systemctl reload nginx
