# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy to server & deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e

            # 1) Update backend code
            cd ~/telegram_invite
            git fetch origin main
            git reset --hard origin/main

            # 2) Install Python dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # 3) Deploy Nginx configuration
            sudo cp deploy/nginx/telegram_invite.conf /etc/nginx/sites-available/telegram_invite
            sudo ln -sf /etc/nginx/sites-available/telegram_invite /etc/nginx/sites-enabled/telegram_invite

            # 4) Restart backend services
            sudo systemctl restart telegram_inviter_celery.service
            sudo systemctl restart telegram_inviter_flask.service

            # 5) Build frontend
            cd frontend
            sudo rm -rf dist
            npm ci
            npm run build

            # 6) Reload Nginx to pick up new static files
            sudo systemctl reload nginx
