# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ——— Шаг-дебаг: проверить секреты ———
      - name: Debug SSH secrets
        run: |
          echo "HOST='${{ secrets.INPUT_HOST }}'"
          echo "PORT='${{ secrets.INPUT_PORT }}'"
          echo "USERNAME='${{ secrets.INPUT_USERNAME }}'"
        shell: bash

      - name: Copy to server & deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.INPUT_HOST }}
          username: ${{ secrets.INPUT_USERNAME }}
          key: ${{ secrets.INPUT_KEY }}
          port: ${{ secrets.INPUT_PORT }}
          script: |
            set -e
            cd ~/telegram_invite
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo cp deploy/nginx/telegram_invite.conf /etc/nginx/sites-available/telegram_invite
            sudo ln -sf /etc/nginx/sites-available/telegram_invite /etc/nginx/sites-enabled/telegram_invite
            sudo systemctl restart telegram_inviter_celery.service
            sudo systemctl restart telegram_inviter_flask.service
            cd frontend
            sudo rm -rf dist
            npm ci
            npm run build
            sudo systemctl reload nginx
