# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy to server & deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}        # 92.113.146.148
          username: ${{ secrets.SERVER_USER }}    # admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}     # 22
          script: |
            set -e

            cd ~/telegram_invite
            git pull origin main

            source venv/bin/activate
            pip install -r requirements.txt

            # ———— deploy nginx config ————
            sudo cp deploy/nginx/telegram_invite.conf /etc/nginx/sites-available/telegram_invite
            sudo ln -sf /etc/nginx/sites-available/telegram_invite /etc/nginx/sites-enabled/telegram_invite
            sudo systemctl reload nginx
            # ————————————————————————

            sudo systemctl restart telegram_inviter_celery.service
            sudo systemctl restart telegram_inviter_flask.service

            cd frontend
            npm ci
            npm run build

            # чтобы nginx отдал новую статическую сборку
            sudo systemctl reload nginx
