name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy to server & restart
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 92.113.146.148
          user: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/telegram_invite
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart telegram_inviter_celery.service telegram_inviter_flask.service
